version: "3.8"
services:
  mongodb_myretail_container:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
      - 9229:9229
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8111:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb_myretail_container
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword