server:
  servlet:
    context-path: /myretail

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: rootpassword
      database: MyRetailDB

redsky:
  api:
    url: https://redsky-uat.perf.target.com/redsky_aggregations/v1/redsky/case_study_v1
    key: 3yUxt7WltYG7MFKPp7uyELi1K40ad2ys

