server:
  servlet:
    context-path: /myretail

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: rootpassword
      database: MyRetailDB
