server:
  servlet:
    context-path: /myretail
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false

management:
  server:
    port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: rootpassword
      database: MyRetailDB

redsky:
  api:
    url: https://redsky-uat.perf.target.com/redsky_aggregations/v1/redsky/case_study_v1
    key: 3yUxt7WltYG7MFKPp7uyELi1K40ad2ys

